### ISSUE TITLE
Formatting the message 

### ISSUE THREAD

**Issue by sreyasvpariyath** [komamitsu/fluency#168] opened 2020-07-19 20:18 UTC
Hi 
I am using `ch.qos.logback.more.appenders.FluencyLogbackAppender` along with Fluency, I was wondering is there is any way to format the log message before it gets emitted.? 
```
<encoder>
			<charset>UTF-8</charset>
			<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS,UTC} UTC: ${PID:- }
				[%15.15thread] %5p [%X{traceId}/%X{spanId}] - %-40.40logger{39} :
				%replace(%.5000msg%n ){'[Pp]assword*([^,]*),', 'password=xxxx,'}%n
			</pattern>
		</encoder>
```
I tried the above config in my logback xml, but could not find any difference. any suggestion.?

**Comment by komamitsu** [comment] 2020-07-23 06:47
To isolate the root cause, how about using `ch.qos.logback.core.ConsoleAppender` w/o FluencyLogbackAppender to check if the replacement works?

**Comment by komamitsu** [comment] 2021-02-14 06:42
I'm closing this issue, but feel free reopen if needed

**Closed by komamitsu** 2021-02-14 06:42 UTC
