### ISSUE TITLE
incorrect maxBufferSize comparison in BufferPool 

### ISSUE THREAD

**Issue by lobeck** [komamitsu/fluency#56] opened 2017-01-05 00:30 UTC
The comparison against `maxBufferSize` in `BufferPool` is reporting the buffer as full, though there is one more increase possible.

A good example for this can be seen in `testBufferFullException`.

initialSize: 64
maxBufferSize: 256

The loop is adding 7 elements, 17 bytes each. 

This results in: `PackedForwardBuffer writing: 17 - size: 128 - remaining: 9`

The test then adds one more, which triggers a `BufferFullException`, which is incorrect at that point. The current buffer is 128 bytes and could be doubled once more to the configured 256 bytes.

It seems, that the increase to 128 pushes `allocatedSize` to 192 at this point: [BufferPool.java#L62](https://github.com/komamitsu/fluency/blob/8209b1ecd8a98fb6fdcbd112c5f40dbfae375344/src/main/java/org/komamitsu/fluency/buffer/BufferPool.java#L62
)

From what i've understood is, that each increase will allocate and return a new and empty buffer, which is then filled with the data from the previous buffer. However i do not understand, why `allocatedSize` is increased there to the combined sizes of the previous buffers. Basically this means, that you can never use more than 50% of `maxBufferSize`.

**Comment by komamitsu** [comment] 2017-01-05 16:19
Yeah. That's a good point.

`BufferPool` in Fluency contains some buffer **chunks**. The sizes of the chunks are multiples of `initialBufferSize`. So it's possible some parts of buffer chunks aren't used. And the total size of used buffer chunks is related to whether buffer is full.

Also, the situation of `testBufferFullException` is really unusual using `StuckSender`. In the test, buffered chunks aren't flushed at all and Fluency keeps to try to expand chunks multiplying by 2.

If we modify the buffer configuration in `testBufferFullException` like this, it can use the total allocated buffer up to 87.5%.
```
PackedForwardBuffer.Config bufferConfig =
                               new PackedForwardBuffer.Config().setChunkInitialSize(64)
                                .setMaxBufferSize(2560).setChunkRetentionSize(64);
```

You can also test it with an actual Fluentd using `FluencyTest#testWithRealFluentd` https://github.com/komamitsu/fluency/blob/master/src/test/java/org/komamitsu/fluency/FluencyTest.java#L1005

In this case, the buffer usage was up to 532676608 / 536870912 = 99%.
```
00:45:55.731 ERROR [pool-3-thread-4] o.k.f.Fluency emit() failed due to buffer full. Flushing buffer. Please try again...
org.komamitsu.fluency.BufferFullException: Buffer is full. config=Config{baseConfig=Config{maxBufferSize=536870912, ackResponseMode=false, fileBackupDir='null', fileBackupPrefix='null', jacksonModules=[]}, chunkInitialSize=1048576, chunkExpandRatio=2.0, chunkRetentionSize=4194304, chunkRetentionTimeMillis=400}, bufferPool=BufferPool{bufferPool={1048576=[], 2097152=[], 8388608=[], 4194304=[]}, allocatedSize=532676608, initialBufferSize=1048576, maxBufferSize=536870912}
	at org.komamitsu.fluency.buffer.PackedForwardBuffer.prepareBuffer(PackedForwardBuffer.java:73)
```

BTW, I found there is a room to improve buffer release a bit in `BufferPool` thanks to your report. I'll take care of it later as another pull request. Thanks

**Comment by jklap** [comment] 2017-04-27 22:01
I'm assuming this might also be related to why calls to getBufferedDataSize() seems to be larger then actual? I haven't dug into this suspected issue yet it's just been an observation with calling getBufferedDataSize() as part of a background monitoring thread.

**Comment by komamitsu** [comment] 2017-05-01 15:12
@jklap I can't reproduce the issue you wrote above. Can you give me an example code that reproduces that?

**Comment by komamitsu** [comment] 2017-05-05 06:16
I'm closing this issue for now. If you still have any trouble, feel free to reopen it.

**Closed by komamitsu** 2017-05-05 06:16 UTC
