### ISSUE TITLE
After a long period of unavailability of fluentd, when fluentd becomes available, fluency stops sending logs without any exceptions

### ISSUE THREAD

**Issue by maxonio** [komamitsu/fluency#164] opened 2020-06-04 09:57 UTC
Hello! I have some troubles with using fluency with logback-more-appenders (https://github.com/sndyuk/logback-more-appenders/blob/master/src/test/resources/logback-appenders-fluentd.xml) with same logback configuration.
I run my spring boot application in docker container and when fluend (td-agent) is available it seems no problem, but when I decided to try to test how this solution will behave if fluentd is unavailable for a long time,I saw that when enabling fluentd, the buffer from fluency sended to fluentd, but after that no new log was sent from the application without any errors on the part of fluency. Why can this happen? Thanks!

**Comment by komamitsu** [comment] 2020-06-21 14:15
I'm not sure this issue was caused by Fluency since the issue sounds related to some components (logback-more-appenders, Spring Boot or etc.) I'd like you to reproduce the issue using Fluency without other libraries / frameworks so that I can look into the issue as a bug of Fluency. BTW, Fluency itself is supposed to be able to handle temporary unavailable of Fluentd.

**Comment by komamitsu** [comment] 2021-02-14 06:44
We recently fixed a few issues and the fixes may resolve this issue.
I'm closing the issue for now, but feel free to reopen it if needed

**Closed by komamitsu** 2021-02-14 06:44 UTC
